version: '3'
services:
  backend:
    build:
      context: ./photo-sharing-server
      dockerfile: Dockerfile
    ports:
      - '5001:5000'
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/postgres"

  frontend:
    build:
      context: ./photo-sharing-client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
    driver: local
