version: '3'
services:
  backend:
    build:
      context: ./photo-sharing-server
      dockerfile: Dockerfile
    ports:
      - '5001:5000'
    volumes:
      - './photo-sharing-server/storage:/app/storage'
      - './photo-sharing-server/photo-sharing-388604-a9033476721a.json:/app/photo-sharing-388604-a9033476721a.json'
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/postgres"
      GOOGLE_APPLICATION_CREDENTIALS: "/app/photo-sharing-388604-a9033476721a.json"
      

  frontend:
    build:
      context: ./photo-sharing-client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  myvolume:
    driver: local
  postgres_data:
    driver: local
